apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: sample-static-rust-axum
build:
  local: {}
  artifacts:
    - image: sample-static-rust-axum-frontend
      context: frontend
      buildpacks:
        builder: ghcr.io/octopilot/builder-jammy-base:0.1.198
    - image: sample-static-rust-axum-api
      context: api
      buildpacks:
        builder: ghcr.io/octopilot/builder-jammy-base:0.1.198
deploy: {}
